name: appplanilha
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.6
  http: ^0.13.3
  provider: ^6.1.2  # ✅ Adicionado para gerenciar o estado do tema
  shared_preferences: ^2.2.3  # ✅ Adicionado para salvar a escolha do usuário

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/placeholder.png
